slam_toolbox:
  ros__parameters:
    # High-performance settings for real-time mapping
    message_filter_queue_size: 1000
    threads: 8
    transform_publish_period: 0.02
    map_update_interval: 0.05
    resolution: 0.05
    max_laser_range: 8.0
    minimum_time_interval: 0.01
    transform_timeout: 1.0
    tf_buffer_duration: 30.0
    stack_size_to_use: 100000000
    minimum_travel_distance: 0.01
    minimum_travel_heading: 0.01
    scan_buffer_size: 50
    throttle_scans: 1
    enable_interactive_mode: true
    
    # Essential frame definitions
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    
    # Plugin params - using accurate solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_loss_function: HuberLoss

    # Scan buffer parameters for better loop closures
    scan_buffer_maximum_scan_distance: 15.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 5.0
    loop_search_maximum_distance: 8.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Scan matcher parameters
    distance_variance_penalty: 0.3
    angle_variance_penalty: 0.6
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.5
    minimum_distance_penalty: 0.3
    use_response_expansion: true

    # Enable scan matching for better tracking
    use_scan_matching: true
    use_scan_barycenter: true
